---
title: "ghost-host: Impact of future extinctions"
author: "Maxwell J. Farrell"
date: "`r format(Sys.time(), '%B %d %Y')`"
output: 
  html_document:
    highlight: default
    toc: no
    toc_depth: 3
    toc_float: true
    theme: yeti
urlcolor: blue
---

<!-- knit with Rscript -e "rmarkdown::render('species_models.Rmd')" -->

<!-- Packages -->

```{r loading packages, echo=F, message=F, warning=F}
require(ape)
require(picante)
require(dplyr)
require(tidyr)
require(ggplot2)
require(phytools)
require(scales)
options(scipen=10)
require(xtable)
require(kableExtra)

```

<!-- Loading Data -->

```{r loading_data, echo=F, message=F, warning=F}

source("./load_data.R")
source("./calc_species_variables.R")

```


```{r sim_extinctions, echo=F, eval=F}

# Calculate host specificities per parasite after extinction
# Setting domestic species to be "LC"
traits$IUCN.Status.1.2[traits$Binomial.1.2%in%dom$host] <- "LC"


if (!file.exists("host_specificities_sim_extinction.rds")) {

calc_specificities <- function(hp_list, phylo){

    # Calculating clade matrix once for whole phylo 
    clade_mat <- clade.matrix(phylo)
    
    host_spec <- data.frame(parasite=sort(unique(hp_list$parasite)))
    
    # pd total
    pd_total <- pd.calc(clade_mat)
    
    host_pd <- sapply(host_spec$parasite, function(para) 
    
          as.numeric(pd.calc(clade_mat, tip.subset=hp_list$host[hp_list$parasite==para], root.edge=FALSE))
    
          ) 
        
    coph <- cophenetic(phylo) #slow that this is inside the function, but okay for now...
    
    host_mpd <- sapply(host_spec$parasite, function(para) 
    
              mean(coph[rownames(coph)%in%hp_list$host[hp_list$parasite==para],
                        colnames(coph)%in%hp_list$host[hp_list$parasite==para]])
          ) 
        
    min_above_zero <- function(x){
    
      if (length(x)>1) {
        min(x[x>0])
      } else {0}
    
    }
        
    host_mntd <- sapply(host_spec$parasite, function(para) 
    
              min_above_zero(coph[rownames(coph)%in%hp_list$host[hp_list$parasite==para], 
                colnames(coph)%in%hp_list$host[hp_list$parasite==para]])
          ) 
    
    
    host_maxD <- sapply(host_spec$parasite, function(para) 
    
              max(coph[rownames(coph)%in%hp_list$host[hp_list$parasite==para], 
                colnames(coph)%in%hp_list$host[hp_list$parasite==para]])
          ) 
    
    
    host_spec <- data.frame(parasite=sort(unique(hp_list$parasite)),
                            mpd=host_mpd, mntd=host_mntd, maxD=host_maxD)
    
    host_spec$creepjump <- with(host_spec, mntd/maxD)
    host_spec$creepjump[is.na(host_spec$creepjump)] <- 0

    return(host_spec)    

}

# Setting domestic species to be "LC"
traits$IUCN.Status.1.2[traits$Binomial.1.2%in%dom$host] <- "LC"

# baseline: up to and including CR (no EX or EW species)
CR <- traits[traits$IUCN.Status.1.2%in%c("DD","LC","NT","VU","EN","CR"),]
hp_list_small <- hp_list[hp_list$host%in%CR$Binomial.1.2,]
tree_small <- drop.tip(tree, setdiff(tree$tip.label,CR$Binomial.1.2))
CR_host_spec <- calc_specificities(hp_list_small, tree_small)
names(CR_host_spec)[2:5] <- paste0(names(CR_host_spec)[2:5],"_CR")

# up to and including EN (no CR, EX or EW species)
EN <- traits[traits$IUCN.Status.1.2%in%c("DD","LC","NT","VU","EN"),]
hp_list_small <- hp_list[hp_list$host%in%EN$Binomial.1.2,]
tree_small <- drop.tip(tree, setdiff(tree$tip.label,EN$Binomial.1.2))
EN_host_spec <- calc_specificities(hp_list_small, tree_small)
names(EN_host_spec)[2:5] <- paste0(names(EN_host_spec)[2:5],"_EN")

# up to and including VU (no EN, CR, EX or EW species)
VU <- traits[traits$IUCN.Status.1.2%in%c("DD","LC","NT","VU"),]
hp_list_small <- hp_list[hp_list$host%in%VU$Binomial.1.2,]
tree_small <- drop.tip(tree, setdiff(tree$tip.label,VU$Binomial.1.2))
VU_host_spec <- calc_specificities(hp_list_small, tree_small)
names(VU_host_spec)[2:5] <- paste0(names(VU_host_spec)[2:5],"_VU")

# up to and including NT (no VU, EN, CR, EX or EW species)
NT <- traits[traits$IUCN.Status.1.2%in%c("DD","LC","NT"),]
hp_list_small <- hp_list[hp_list$host%in%NT$Binomial.1.2,]
tree_small <- drop.tip(tree, setdiff(tree$tip.label,NT$Binomial.1.2))
NT_host_spec <- calc_specificities(hp_list_small, tree_small)
names(NT_host_spec)[2:5] <- paste0(names(NT_host_spec)[2:5],"_NT")

# up to and including LC (no NT, VU, EN, CR, EX or EW species)
LC <- traits[traits$IUCN.Status.1.2%in%c("DD","LC"),]
hp_list_small <- hp_list[hp_list$host%in%LC$Binomial.1.2,]
tree_small <- drop.tip(tree, setdiff(tree$tip.label,LC$Binomial.1.2))
LC_host_spec <- calc_specificities(hp_list_small, tree_small)
names(LC_host_spec)[2:5] <- paste0(names(LC_host_spec)[2:5],"_LC")

sim_ext <- left_join(CR_host_spec, EN_host_spec)
sim_ext <- left_join(sim_ext, VU_host_spec)
sim_ext <- left_join(sim_ext, NT_host_spec)
sim_ext <- left_join(sim_ext, LC_host_spec)

saveRDS(sim_ext, "host_specificities_sim_extinction.rds")

} else {sim_ext <- readRDS("host_specificities_sim_extinction.rds")}


```

```{r plots, echo=F, eval=T}

sim_ext <- readRDS("host_specificities_sim_extinction.rds")

# joining simulated extinctions with contemporary host specificities ("host_spec")
sim_ext <- left_join(host_spec, sim_ext)

diffs <- sim_ext$mpd_CR - sim_ext$mpd
names(diffs) <- sim_ext$parasite
hp_list[hp_list$parasite %in% names(sort(diffs))[1],]

# hp-List includes recently extinct species, use mpd_CR to represent contemporary HP interactions.

ggplot(sim_ext, aes(mpd_CR, mpd_LC)) + geom_point(alpha=0.2) + theme_classic() + 
                                      xlab("MPD: No extinction") + ylab("MPD: CR+EN+VU+NT extinction") +
                                      geom_text(aes(label=ifelse(parasite%in%c("Ophidascaris robertsi", "Neodiplostomum intermedium"),as.character(parasite),'')),hjust=0,vjust=-0.5) +  
                                      geom_point(data=sim_ext[sim_ext$parasite%in%c("Ophidascaris robertsi", "Neodiplostomum intermedium"),], aes(mpd_CR, mpd_LC), color='dodgerblue2', size=2)

ggsave("../plots_tables/mpd_change_XYplot.pdf", width=7, height=6)
ggsave("../plots_tables/mpd_change_XYplot.png", width=7, height=6)


mpd_diffs <- with(sim_ext, data.frame(parasite=parasite,
                                      CR_loss=mpd_EN-mpd_CR,
                                      EN_loss=mpd_VU-mpd_CR,
                                      VU_loss=mpd_NT-mpd_CR,
                                      NT_loss=mpd_LC-mpd_CR))

mpd_diffs <- mpd_diffs %>%
                gather(key, value, -parasite) 

mpd_diffs$key <- factor(mpd_diffs$key, levels = c("CR_loss","EN_loss","VU_loss","NT_loss"))

mpd_diffs_nonzero <- mpd_diffs[mpd_diffs$value!=0 & !is.na(mpd_diffs$value),]

require(ggallin) # for pseudolog10_trans - doesn't look as nice though (can't see outliers)
require(ggforce)

cbPalette <- c("#999999", "#E69F00", "#56B4E9", "#009E73", "#F0E442", "#0072B2", "#D55E00", "#CC79A7") # with grey as first instead of black ("#000000")

mpd_changes_plot <- ggplot(mpd_diffs_nonzero, aes(key, value)) + 
                        geom_violin(aes(colour=key, fill=key), alpha=0.8) + 
                        theme_classic() + theme(legend.position = "none") + 
                        scale_x_discrete(labels=c("CR","CR+EN","CR+EN+VU","CR+EN+VU+NT")) + 
                        xlab("Extinction scenario") + ylab("Change in MPD") + 
                        scale_colour_manual(values=cbPalette[c(3,4,2,7)]) +
                        scale_fill_manual(values=cbPalette[c(3,4,2,7)]) 


ggsave("../plots_tables/mpd_changes.pdf", mpd_changes_plot, width=5, height=3)
ggsave("../plots_tables/mpd_changes.png", mpd_changes_plot, width=5, height=3)


# Picking out example phylogenies

mpd_change <- sim_ext$mpd_LC - sim_ext$mpd_CR
names(mpd_change) <- sim_ext$parasite
mpd_change_table <- rev(sort(mpd_change))

source("sim_functions.R")

# MOST MPD GAINED
# head(mpd_change_table, 15)

# hp_list[hp_list$parasite=="Ophidascaris robertsi",]
tmp_hosts <- hp_list$host[hp_list$parasite=="Ophidascaris robertsi"]

tmp_tree <- drop.tip(tree, setdiff(tree$tip.label,tmp_hosts))
treeA <- drop.tip(tree, setdiff(tree$tip.label,tmp_hosts))
tmp_traits <- traits[traits$Binomial.1.2%in%tmp_hosts,]
tmp_LC <- tmp_traits[tmp_traits$IUCN.Status.1.2%in%c("DD","LC"),]

droptipTree(tree=tmp_tree, tip=tmp_tree$tip.label[!tmp_tree$tip.label%in%tmp_LC$Binomial.1.2], tip.labs=TRUE)

pdf("../plots_tables/Ophidascaris_extinction.pdf", width=10, height=5)
droptipTree(tree=tmp_tree, tip=tmp_tree$tip.label[!tmp_tree$tip.label%in%tmp_LC$Binomial.1.2], tip.labs=TRUE)
add.scale.bar(1, 1, length = 10)
dev.off()

# MOST MPD LOST
# tail(mpd_change_table, 15)

# hp_list[hp_list$parasite=="Neodiplostomum intermedium",]
tmp_hosts <- hp_list$host[hp_list$parasite=="Neodiplostomum intermedium"]
# also a rodent / marsupial example - good to pair with Ophidascaris! (D. maculatus infected by both)

tmp_tree <- drop.tip(tree, setdiff(tree$tip.label,tmp_hosts))
treeB <- drop.tip(tree, setdiff(tree$tip.label,tmp_hosts))
tmp_traits <- traits[traits$Binomial.1.2%in%tmp_hosts,]
tmp_LC <- tmp_traits[tmp_traits$IUCN.Status.1.2%in%c("DD","LC"),]

# droptipTree(tree=tmp_tree, tip=tmp_tree$tip.label[!tmp_tree$tip.label%in%tmp_LC$Binomial.1.2], tip.labs=TRUE)

pdf("../plots_tables/Neodiplostomum_extinction.pdf", width=7.28054784897, height=3.35)
droptipTree(tree=tmp_tree, tip=tmp_tree$tip.label[!tmp_tree$tip.label%in%tmp_LC$Binomial.1.2], tip.labs=TRUE)
add.scale.bar(1, 1, length = 10)
dev.off()

# pdf("../plots_tables/kronoviz.pdf", width=10, height=10)
# par(mar=c(5.1, 4.1, 4.1, 6.1))
# kronoviz(c(treeA, treeB), show.tip.label = TRUE)
# dev.off()

# args(kronoviz)



# sim_ext <- sim_ext %>%
#                 gather(key, value, -parasite) %>%
#                 separate(key, into = c("metric", "scenario"), sep = "_") 

# sim_ext$scenario <- factor(sim_ext$scenario, levels = c("CR","EN","VU","NT","LC"))

# sort(unique(sim_ext$metric))
# ggplot(sim_ext[sim_ext$metric=="mpd",], aes(scenario, value)) + geom_violin() + scale_y_continuous(trans='log10')
# ggplot(sim_ext[sim_ext$metric=="mntd",], aes(scenario, value)) + geom_violin() + scale_y_continuous(trans='log10')
# ggplot(sim_ext[sim_ext$metric=="maxD",], aes(scenario, value)) + geom_violin()
# ggplot(sim_ext[sim_ext$metric=="creepjump",], aes(scenario, value)) + geom_violin()



```


```{r ordered_extinction, echo=F, eval=T}

calc_mpd <- function(hp_list, coph){

    host_spec <- data.frame(parasite=sort(unique(hp_list$parasite)))
        
    host_mpd <- sapply(host_spec$parasite, function(para) 
    
              mean(coph[rownames(coph)%in%hp_list$host[hp_list$parasite==para],
                        colnames(coph)%in%hp_list$host[hp_list$parasite==para]])
          ) 
        
    host_spec <- data.frame(parasite=sort(unique(hp_list$parasite)),
                            mpd=host_mpd)
    return(host_spec)    
}


# simulations only for T. cruzi
# baseline: up to and including CR (no EX or EW species)
base <- traits[traits$IUCN.Status.1.2%in%c("DD","LC","NT","VU","EN","CR"),]
hp_list_small <- hp_list[hp_list$host%in%base$Binomial.1.2,]
tree_small <- drop.tip(tree, setdiff(tree$tip.label,base$Binomial.1.2))
coph <- cophenetic(tree_small)
base_mpd <- calc_mpd(hp_list_small, coph)

LC_hosts <- unique(base$Binomial.1.2[base$IUCN.Status.1.2%in%c("CR", "EN", "VU","NT")])

dom_humans <- c(unique(dom$host), "Homo_sapiens")

paras_impacted <- "Trypanosoma cruzi"
hp_list_impacted <- hp_list_small[hp_list_small$parasite%in%paras_impacted,]
hosts_lost <- unique(hp_list_impacted$host)

# remove dom + humans
hosts_lost <- setdiff(hosts_lost, dom_humans)

coph <- cophenetic(tree)

t_cruzi <- base_mpd[base_mpd$parasite %in% paras_impacted,]
t_cruzi$n_hosts_removed <- 0
t_cruzi$rep_n <- 0

t_cruzi_noext <- t_cruzi

set.seed(1989)

n_rep <- 200

for (j in 1:n_rep) {

      ext_order <- sample(length(hosts_lost))

      for (i in seq_along(ext_order)) {
      
          print(paste("rep:",j, "--", i, "of", length(hosts_lost), "hosts removed"))

          hosts_to_remove <- hosts_lost[ext_order[1:i]]
          hp_list_small <- hp_list_impacted[!hp_list_impacted$host%in%hosts_to_remove,]
          
          if(nrow(hp_list_small)>0){ # doing this in case all parasites go extinct
              
              new_mpd <- calc_mpd(hp_list_small, coph)
              new_mpd$n_hosts_removed <- i
              new_mpd$rep_n <- j
              t_cruzi_noext$rep_n <- j #bind initial state for plotting
              t_cruzi <- rbind(t_cruzi_noext,t_cruzi, new_mpd)
      
        }
      }      
}

saveRDS(t_cruzi, "t_cruzi_simExt.rds")

t_cruzi_plot <- t_cruzi %>%
  ggplot( aes(x=n_hosts_removed, y=mpd, group=as.factor(rep_n))) +
    geom_line(alpha=0.15, size=0.25) + theme_classic() +
    xlab("Number of hosts lost") + ylab("MPD") +
    scale_x_continuous(expand = c(0, 0), limits = c(0, 58)) + 
    scale_y_continuous(expand = c(0, 0), limits = c(120, 240)) 

     
ggsave("../plots_tables/t_cruzi.pdf", t_cruzi_plot, width=5, height=3)
ggsave("../plots_tables/t_cruzi.png", t_cruzi_plot, width=5, height=3)


library("cowplot")
plot_grid(mpd_changes_plot, t_cruzi_plot, 
          labels = c("A)", "B)"),
          nrow = 2, label_size=11, hjust=0)

ggsave("../plots_tables/future_ext_paired.pdf", width=5, height=6)
ggsave("../plots_tables/future_ext_paired.png", width=5, height=6)

```